-- create schema and switch to it
CREATE SCHEMA IF NOT EXISTS APP;

create user APP_USER password 'APP_USER';

grant all on schema APP to APP_USER;

SET SCHEMA APP;

-- USERS table
CREATE TABLE IF NOT EXISTS USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TYPE VARCHAR(50)    NOT NULL,
    LOGIN VARCHAR(255)  NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255)  NOT NULL,
    VERSION INT DEFAULT 0 NOT NULL,
    ACTIVE  BOOLEAN DEFAULT FALSE NOT NULL
    );

-- GAME_WORLD table
CREATE TABLE IF NOT EXISTS GAME_WORLD (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    WORLD_NAME VARCHAR(255)       NOT NULL,
    WORLD_DESCRIPTION VARCHAR(255),
    VERSION INT DEFAULT 0 NOT NULL
    );

-- CHARACTERS table
CREATE TABLE IF NOT EXISTS CHARACTERS (
                                          ID INT AUTO_INCREMENT PRIMARY KEY,
                                          JOB VARCHAR(50)     NOT NULL,
    NAME VARCHAR(255)   NOT NULL,
    VERSION INT DEFAULT 0 NOT NULL,
    USER_ID INT         NOT NULL,
    IMAGEURL VARCHAR(255),
    GAMEWORLD_ID INT    NOT NULL,
    FOREIGN KEY (USER_ID)      REFERENCES USERS(ID),
    FOREIGN KEY (GAMEWORLD_ID) REFERENCES GAME_WORLD(ID)
    );
